name: charmed-mysql # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '8.0.32-0' # just for humans, typically '1.2+git' or '1.3.2'
summary: MySQL server in a snap. # 79 char long summary
description: |
  The MySQL software delivers a very fast, multithreaded, multi-user,
  and robust SQL (Structured Query Language) database server. MySQL
  Server is intended for mission-critical, heavy-load production
  systems as well as for embedding into mass-deployed software.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

system-usernames:
  snap_daemon: shared

package-repositories:
  - type: apt
    components:
      - main
    suites:
      - jammy
    key-id: 630239CC130E1A7FD81A27B140976EAF437D05B5
    url: http://security.ubuntu.com/ubuntu/
  - type: apt
    components:
      - main
    suites:
      - jammy
    key-id: 4D1BB29D63D98E422B2113B19334A25F8507EFA5
    url: http://repo.percona.com/percona/apt

layout:
  /var/lib/mysql-files:
    bind: $SNAP_COMMON/var/lib/mysql-files
  /usr/lib/mysqlrouter:
    symlink: $SNAP/usr/lib/mysqlrouter
  /usr/lib/mysql-router:
    symlink: $SNAP/usr/lib/mysql-router
  /etc/mysqlrouter:
    bind: $SNAP_DATA/etc/mysqlrouter
  /var/lib/mysqlrouter:
    bind: $SNAP_COMMON/var/lib/mysqlrouter
  /var/log/mysqlrouter:
    bind: $SNAP_COMMON/var/log/mysqlrouter
  /usr/lib/mysqlsh:
    bind: $SNAP/lib/mysqlsh


hooks:
  install:
    plugs:
      - network
      - network-bind
  configure:
    plugs:
      - network

slots:
  logs:
    interface: content
    source:
      read:
        - $SNAP_COMMON/var/log/mysql
  mysqlrouter-sockets:
    interface: content
    content: socket-directory
    write:
      - $SNAP_COMMON/run/mysqlrouter

apps:
  mysql:
    command: usr/bin/mysql
    plugs:
      - network
  mysqld:
    command: start-mysqld.sh
    daemon: simple
    install-mode: disable
    plugs:
      - network
      - network-bind
  mysqlsh:
    command: usr/bin/mysqlsh
    plugs:
      - network
  mysqlrouter:
    command: run-mysql-router.sh
    plugs:
      - network
  mysqlrouter-service:
    command: start-mysql-router.sh
    daemon: simple
    install-mode: disable
    plugs:
      - network
      - network-bind
  xtrabackup:
    command: usr/bin/xtrabackup
  xbcloud:
    command: usr/bin/xbcloud
    plugs:
      - network
  xbstream:
    command: usr/bin/xbstream
  mysqld-exporter:
    command: start-mysqld-exporter.sh
    daemon: simple
    plugs:
      - network
      - network-bind
parts:
  pin-mysql-apt:
    plugin: nil
    override-pull: |
      printf "Package: mysql-server-8.0\nPin: version 8.0.32*\nPin-Priority: 1001\n" > /etc/apt/preferences.d/mysql
      printf "\nPackage: mysql-router\nPin: version 8.0.32*\nPin-Priority: 1001\n" >> /etc/apt/preferences.d/mysql
      printf "\nPackage: percona-xtrabackup-80\nPin: version 8.0.32*\nPin-Priority: 1001\n" >> /etc/apt/preferences.d/mysql
  package-mysql-shell:
    plugin: dump
    source: https://downloads.mysql.com/archives/get/p/43/file/mysql-shell-8.0.32-linux-glibc2.12-x86-64bit.tar.gz
    organize:
      bin: usr/bin
      libexec: usr/libexec
      lib: usr/lib
      share: usr/share
  packages-deb:
    plugin: nil
    stage-packages:
      - mysql-server-8.0
      - mysql-router
      - percona-xtrabackup-80
      - util-linux
    after:
      - pin-mysql-apt
  wrapper:
    plugin: dump
    source: snap/local
  mysqld-exporter:
    plugin: dump
    source: https://github.com/prometheus/mysqld_exporter/releases/download/v0.14.0/mysqld_exporter-0.14.0.linux-amd64.tar.gz
    source-type: tar
    source-checksum: sha256/c17402137a4e9745f593127f162c1003298910cb8aa7d05bee3384738de094ae
    organize:
      'mysqld_exporter': usr/bin/mysqld_exporter
    prime:
      - -LICENSE
      - -NOTICE
