name: Check Version
on:
  workflow_dispatch:
  pull_request:

jobs:
  check-version:
    runs-on: ubuntu-22.04
    timeout-minutes: 15
    steps:
      - name: 'Foresight: Collect workflow telemetry'
        uses: runforesight/foresight-workflow-kit-action@v1
      - uses: actions/checkout@v3
      - name: Install yq
        run: sudo snap install yq
      - name: Compare versions
        run: |
          SNAP_VERSION=$(yq .version snap/snapcraft.yaml)
          APT_VERSION=$(apt info mysql-server | grep Version | cut -c10-)
          APT_VERSION=${APT_VERSION::-15}
          if [ "$SNAP_VERSION" != "$APT_VERSION" ]; then
              echo "VERSION MISMATCH DETECTED"
              echo "Snap version: $SNAP_VERSION"
              echo "APT version: $APT_VERSION"
              exit 1
          fi
