name: Check Version
on:
  workflow_dispatch:
  pull_request:

jobs:
  check-version:
    runs-on: ubuntu-22.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - name: Install yq
        run: sudo snap install yq
      - name: Compare versions
        run: |
          SNAP_VERSION=$(yq .version snap/snapcraft.yaml)
          sudo apt-get update
          APT_VERSION=$(apt-cache show mysql-server-8.0 | awk '/Version: /{print $2; exit}')
          APT_VERSION=${APT_VERSION::-17}
          if [ "$SNAP_VERSION" != "$APT_VERSION" ]; then
              echo "VERSION MISMATCH DETECTED"
              echo "Snap version: $SNAP_VERSION"
              echo "APT version: $APT_VERSION"
              exit 1
          fi
